[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'tyru/caw.vim.git'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'ngmy/vim-rubocop'

[[plugins]]
repo = 'thoughtbot/vim-rspec'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
